# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QApplication, QMainWindow 
import hashlib
import diaset as bot
import kitap1366 as kitap1366
import aletler as aletlerr
import kitap as kitap
import diaset1366
import aletler1366 as aletler1366
from PyQt6.QtWidgets import QApplication, QLabel, QWidget, QVBoxLayout
from PyQt6.QtGui import QFont, QFontDatabase
import sys
import os
import ciftcimain
import otofarm

cozunurluk = "1920x1080"


def getchecksum():
    md5_hash = hashlib.md5()
    file = open(''.join(sys.argv), "rb")
    md5_hash.update(file.read())
    digest = md5_hash.hexdigest()
    return digest


# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets







class Ui_aletler(object):
    def setupUi(self, enchantForm):
        font_path = "resources/ProggyClean.ttf"

        # QFontDatabase ile fontu yü2kle
        font_id = QFontDatabase.addApplicationFont(font_path)
        font_family = QFontDatabase.applicationFontFamilies(font_id)

        # Yüklenen fontu kullanarak bir QFont oluştur
        custom_font = QFont(font_family, 12)
        enchantForm.setObjectName("enchantForm")
        enchantForm.resize(552, 447)
        enchantForm.setStyleSheet("background-color: rgb(08, 08, 08)")
        self.setler = QtWidgets.QWidget(parent=enchantForm)
        self.setler.setStyleSheet("")
        self.setler.setObjectName("setler")
        self.arkaplan = QtWidgets.QWidget(parent=self.setler)
        self.arkaplan.setGeometry(QtCore.QRect(10, 0, 811, 451))
        font = QtGui.QFont()
        
        self.arkaplan.setFont(custom_font)
        self.arkaplan.setStyleSheet("border:0px solid white;\n"
"background-color:rgb(8,8,8);\n"
"border-radius:14px;")
        self.arkaplan.setObjectName("arkaplan")
        self.kitaplarBtn = QtWidgets.QPushButton(parent=self.arkaplan)
        self.kitaplarBtn.setGeometry(QtCore.QRect(220, 50, 95, 35))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.kitaplarBtn.setFont(custom_font)
        self.kitaplarBtn.setWhatsThis("")
        self.kitaplarBtn.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.kitaplarBtn.setAutoRepeat(False)
        self.kitaplarBtn.setAutoExclusive(False)
        self.kitaplarBtn.setAutoDefault(False)
        self.kitaplarBtn.setDefault(True)
        self.kitaplarBtn.setFlat(False)
        self.kitaplarBtn.setObjectName("kitaplarBtn")
        self.setlerBtn = QtWidgets.QPushButton(parent=self.arkaplan)
        self.setlerBtn.setGeometry(QtCore.QRect(20, 50, 95, 35))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.setlerBtn.setFont(custom_font)
        self.setlerBtn.setWhatsThis("")
        self.setlerBtn.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.setlerBtn.setAutoRepeat(False)
        self.setlerBtn.setAutoExclusive(False)
        self.setlerBtn.setAutoDefault(False)
        self.setlerBtn.setDefault(True)
        self.setlerBtn.setFlat(False)
        self.setlerBtn.setObjectName("setlerBtn")
        self.sayfalar = QtWidgets.QStackedWidget(parent=self.arkaplan)
        self.sayfalar.setGeometry(QtCore.QRect(20, 90, 491, 321))
        self.sayfalar.setStyleSheet("border:0px solid white;\n"
"background-color:rgb(8,8,8);\n"
"border-radius:14px;")
        self.sayfalar.setObjectName("sayfalar")
        self.setlerSayfa = QtWidgets.QWidget()
        self.setlerSayfa.setObjectName("setlerSayfa")
        self.setlerGroupBox = QtWidgets.QGroupBox(parent=self.setlerSayfa)
        self.setlerGroupBox.setEnabled(True)
        self.setlerGroupBox.setGeometry(QtCore.QRect(0, 0, 491, 271))
        self.setlerGroupBox.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"border-radius:4px;")
        self.setlerGroupBox.setTitle("")
        self.setlerGroupBox.setObjectName("setlerGroupBox")
        self.diakaskCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.diakaskCheckbox.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.diakaskCheckbox.setMouseTracking(False)
        self.diakaskCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diakaskCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diakaskCheckbox.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/transparent.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("resources/check.png"), QtGui.QIcon.Mode.Selected, QtGui.QIcon.State.On)
        self.diakaskCheckbox.setIcon(icon)
        self.diakaskCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.diakaskCheckbox.setShortcut("")
        self.diakaskCheckbox.setCheckable(True)
        self.diakaskCheckbox.setChecked(False)
        self.diakaskCheckbox.setAutoDefault(False)
        self.diakaskCheckbox.setDefault(False)
        self.diakaskCheckbox.setFlat(False)
        self.diakaskCheckbox.setObjectName("diakaskCheckbox")
        self.label_3 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_3.setGeometry(QtCore.QRect(45, 20, 71, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_3.setFont(custom_font)
        self.label_3.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_14.setGeometry(QtCore.QRect(45, 50, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_14.setFont(custom_font)
        self.label_14.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_14.setObjectName("label_14")
        self.diaChestPlateCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.diaChestPlateCheckbox.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.diaChestPlateCheckbox.setMouseTracking(False)
        self.diaChestPlateCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diaChestPlateCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diaChestPlateCheckbox.setText("")
        self.diaChestPlateCheckbox.setIcon(icon)
        self.diaChestPlateCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.diaChestPlateCheckbox.setShortcut("")
        self.diaChestPlateCheckbox.setCheckable(True)
        self.diaChestPlateCheckbox.setChecked(False)
        self.diaChestPlateCheckbox.setAutoDefault(False)
        self.diaChestPlateCheckbox.setDefault(False)
        self.diaChestPlateCheckbox.setFlat(False)
        self.diaChestPlateCheckbox.setObjectName("diaChestPlateCheckbox")
        self.label_15 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_15.setGeometry(QtCore.QRect(45, 110, 111, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_15.setFont(custom_font)
        self.label_15.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_16.setGeometry(QtCore.QRect(45, 80, 111, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_16.setFont(custom_font)
        self.label_16.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_16.setObjectName("label_16")
        self.diabotCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.diabotCheckbox.setGeometry(QtCore.QRect(20, 110, 16, 16))
        self.diabotCheckbox.setMouseTracking(False)
        self.diabotCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diabotCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diabotCheckbox.setText("")
        self.diabotCheckbox.setIcon(icon)
        self.diabotCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.diabotCheckbox.setShortcut("")
        self.diabotCheckbox.setCheckable(True)
        self.diabotCheckbox.setChecked(False)
        self.diabotCheckbox.setAutoDefault(False)
        self.diabotCheckbox.setDefault(False)
        self.diabotCheckbox.setFlat(False)
        self.diabotCheckbox.setObjectName("diabotCheckbox")
        self.diapntCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.diapntCheckbox.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.diapntCheckbox.setMouseTracking(False)
        self.diapntCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diapntCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diapntCheckbox.setText("")
        self.diapntCheckbox.setIcon(icon)
        self.diapntCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.diapntCheckbox.setShortcut("")
        self.diapntCheckbox.setCheckable(True)
        self.diapntCheckbox.setChecked(False)
        self.diapntCheckbox.setAutoDefault(False)
        self.diapntCheckbox.setDefault(False)
        self.diapntCheckbox.setFlat(False)
        self.diapntCheckbox.setObjectName("diapntCheckbox")
        self.label_17 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_17.setGeometry(QtCore.QRect(45, 170, 141, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_17.setFont(custom_font)
        self.label_17.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_18.setGeometry(QtCore.QRect(45, 140, 101, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_18.setFont(custom_font)
        self.label_18.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_18.setObjectName("label_18")
        self.titChestPlateCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.titChestPlateCheckBox.setGeometry(QtCore.QRect(20, 170, 16, 16))
        self.titChestPlateCheckBox.setMouseTracking(False)
        self.titChestPlateCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titChestPlateCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.titChestPlateCheckBox.setText("")
        self.titChestPlateCheckBox.setIcon(icon)
        self.titChestPlateCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.titChestPlateCheckBox.setShortcut("")
        self.titChestPlateCheckBox.setCheckable(True)
        self.titChestPlateCheckBox.setChecked(False)
        self.titChestPlateCheckBox.setAutoDefault(False)
        self.titChestPlateCheckBox.setDefault(False)
        self.titChestPlateCheckBox.setFlat(False)
        self.titChestPlateCheckBox.setObjectName("titChestPlateCheckBox")
        self.titkaskCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.titkaskCheckbox.setGeometry(QtCore.QRect(20, 140, 16, 16))
        self.titkaskCheckbox.setMouseTracking(False)
        self.titkaskCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titkaskCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.titkaskCheckbox.setText("")
        self.titkaskCheckbox.setIcon(icon)
        self.titkaskCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.titkaskCheckbox.setShortcut("")
        self.titkaskCheckbox.setCheckable(True)
        self.titkaskCheckbox.setChecked(False)
        self.titkaskCheckbox.setAutoDefault(False)
        self.titkaskCheckbox.setDefault(False)
        self.titkaskCheckbox.setFlat(False)
        self.titkaskCheckbox.setObjectName("titkaskCheckbox")
        self.label_19 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_19.setGeometry(QtCore.QRect(45, 230, 91, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_19.setFont(custom_font)
        self.label_19.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_20.setGeometry(QtCore.QRect(45, 200, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_20.setFont(custom_font)
        self.label_20.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_20.setObjectName("label_20")
        self.titbotCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.titbotCheckbox.setGeometry(QtCore.QRect(20, 230, 16, 16))
        self.titbotCheckbox.setMouseTracking(False)
        self.titbotCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titbotCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.titbotCheckbox.setText("")
        self.titbotCheckbox.setIcon(icon)
        self.titbotCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.titbotCheckbox.setShortcut("")
        self.titbotCheckbox.setCheckable(True)
        self.titbotCheckbox.setChecked(False)
        self.titbotCheckbox.setAutoDefault(False)
        self.titbotCheckbox.setDefault(False)
        self.titbotCheckbox.setFlat(False)
        self.titbotCheckbox.setObjectName("titbotCheckbox")
        self.titpantCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.titpantCheckbox.setGeometry(QtCore.QRect(20, 200, 16, 16))
        self.titpantCheckbox.setMouseTracking(False)
        self.titpantCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titpantCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.titpantCheckbox.setText("")
        self.titpantCheckbox.setIcon(icon)
        self.titpantCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.titpantCheckbox.setShortcut("")
        self.titpantCheckbox.setCheckable(True)
        self.titpantCheckbox.setChecked(False)
        self.titpantCheckbox.setAutoDefault(False)
        self.titpantCheckbox.setDefault(False)
        self.titpantCheckbox.setFlat(False)
        self.titpantCheckbox.setObjectName("titpantCheckbox")
        self.label_21 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_21.setGeometry(QtCore.QRect(190, 20, 81, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_21.setFont(custom_font)
        self.label_21.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_21.setObjectName("label_21")
        self.kilicCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.kilicCheckbox.setGeometry(QtCore.QRect(165, 20, 16, 16))
        self.kilicCheckbox.setMouseTracking(False)
        self.kilicCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.kilicCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.kilicCheckbox.setText("")
        self.kilicCheckbox.setIcon(icon)
        self.kilicCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.kilicCheckbox.setShortcut("")
        self.kilicCheckbox.setCheckable(True)
        self.kilicCheckbox.setChecked(False)
        self.kilicCheckbox.setAutoDefault(False)
        self.kilicCheckbox.setDefault(False)
        self.kilicCheckbox.setFlat(False)
        self.kilicCheckbox.setObjectName("kilicCheckbox")
        self.label_30 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_30.setGeometry(QtCore.QRect(190, 80, 81, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_30.setFont(custom_font)
        self.label_30.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_30.setObjectName("label_30")
        self.yayCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.yayCheckbox.setGeometry(QtCore.QRect(165, 80, 16, 16))
        self.yayCheckbox.setMouseTracking(False)
        self.yayCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.yayCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.yayCheckbox.setText("")
        self.yayCheckbox.setIcon(icon)
        self.yayCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.yayCheckbox.setShortcut("")
        self.yayCheckbox.setCheckable(True)
        self.yayCheckbox.setChecked(False)
        self.yayCheckbox.setAutoDefault(False)
        self.yayCheckbox.setDefault(False)
        self.yayCheckbox.setFlat(False)
        self.yayCheckbox.setObjectName("yayCheckbox")
        self.label_31 = QtWidgets.QLabel(parent=self.setlerGroupBox)
        self.label_31.setGeometry(QtCore.QRect(190, 50, 101, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_31.setFont(custom_font)
        self.label_31.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_31.setObjectName("label_31")
        self.titanyumKilicCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox)
        self.titanyumKilicCheckBox.setGeometry(QtCore.QRect(165, 50, 16, 16))
        self.titanyumKilicCheckBox.setMouseTracking(False)
        self.titanyumKilicCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.titanyumKilicCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.titanyumKilicCheckBox.setText("")
        self.titanyumKilicCheckBox.setIcon(icon)
        self.titanyumKilicCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.titanyumKilicCheckBox.setShortcut("")
        self.titanyumKilicCheckBox.setCheckable(True)
        self.titanyumKilicCheckBox.setChecked(False)
        self.titanyumKilicCheckBox.setAutoDefault(False)
        self.titanyumKilicCheckBox.setDefault(False)
        self.titanyumKilicCheckBox.setFlat(False)
        self.titanyumKilicCheckBox.setObjectName("titanyumKilicCheckBox")
        self.startButtonsetler = QtWidgets.QPushButton(parent=self.setlerSayfa)
        self.startButtonsetler.setGeometry(QtCore.QRect(0, 280, 491, 41))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.startButtonsetler.setFont(custom_font)
        self.startButtonsetler.setWhatsThis("")
        self.startButtonsetler.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.startButtonsetler.setAutoRepeat(False)
        self.startButtonsetler.setAutoExclusive(False)
        self.startButtonsetler.setAutoDefault(False)
        self.startButtonsetler.setDefault(True)
        self.startButtonsetler.setFlat(False)
        self.startButtonsetler.setObjectName("startButtonsetler")
        self.sayfalar.addWidget(self.setlerSayfa)
        self.ciftciSayfa = QtWidgets.QWidget()
        self.ciftciSayfa.setObjectName("ciftciSayfa")
        self.setlerGroupBox_4 = QtWidgets.QGroupBox(parent=self.ciftciSayfa)
        self.setlerGroupBox_4.setEnabled(True)
        self.setlerGroupBox_4.setGeometry(QtCore.QRect(0, 0, 491, 271))
        self.setlerGroupBox_4.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"border-radius:4px;")
        self.setlerGroupBox_4.setTitle("")
        self.setlerGroupBox_4.setObjectName("setlerGroupBox_4")
        self.diakaskCheckbox_4 = QtWidgets.QPushButton(parent=self.setlerGroupBox_4)
        self.diakaskCheckbox_4.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.diakaskCheckbox_4.setMouseTracking(False)
        self.diakaskCheckbox_4.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diakaskCheckbox_4.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diakaskCheckbox_4.setText("")
        self.diakaskCheckbox_4.setIcon(icon)
        self.diakaskCheckbox_4.setIconSize(QtCore.QSize(10, 15))
        self.diakaskCheckbox_4.setShortcut("")
        self.diakaskCheckbox_4.setCheckable(True)
        self.diakaskCheckbox_4.setChecked(False)
        self.diakaskCheckbox_4.setAutoDefault(False)
        self.diakaskCheckbox_4.setDefault(False)
        self.diakaskCheckbox_4.setFlat(False)
        self.diakaskCheckbox_4.setObjectName("diakaskCheckbox_4")
        self.label_6 = QtWidgets.QLabel(parent=self.setlerGroupBox_4)
        self.label_6.setGeometry(QtCore.QRect(45, 20, 181, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_6.setFont(custom_font)
        self.label_6.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_6.setObjectName("label_6")
        self.label_44 = QtWidgets.QLabel(parent=self.setlerGroupBox_4)
        self.label_44.setGeometry(QtCore.QRect(45, 50, 201, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_44.setFont(custom_font)
        self.label_44.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_44.setObjectName("label_44")
        self.diaChestPlateCheckbox_4 = QtWidgets.QPushButton(parent=self.setlerGroupBox_4)
        self.diaChestPlateCheckbox_4.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.diaChestPlateCheckbox_4.setMouseTracking(False)
        self.diaChestPlateCheckbox_4.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.diaChestPlateCheckbox_4.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.diaChestPlateCheckbox_4.setText("")
        self.diaChestPlateCheckbox_4.setIcon(icon)
        self.diaChestPlateCheckbox_4.setIconSize(QtCore.QSize(10, 15))
        self.diaChestPlateCheckbox_4.setShortcut("")
        self.diaChestPlateCheckbox_4.setCheckable(True)
        self.diaChestPlateCheckbox_4.setChecked(False)
        self.diaChestPlateCheckbox_4.setAutoDefault(False)
        self.diaChestPlateCheckbox_4.setDefault(False)
        self.diaChestPlateCheckbox_4.setFlat(False)
        self.diaChestPlateCheckbox_4.setObjectName("diaChestPlateCheckbox_4")
        self.widget = QtWidgets.QWidget(parent=self.setlerGroupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 90, 471, 171))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label.setFont(custom_font)
        self.label.setStyleSheet("color:white;border:0px;")
        self.label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 34, 450, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_2.setFont(custom_font)
        self.label_2.setStyleSheet("color:white;border:0px;")
        self.label_2.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_2.setObjectName("label_2")
        self.startButtonciftci = QtWidgets.QPushButton(parent=self.ciftciSayfa)
        self.startButtonciftci.setGeometry(QtCore.QRect(0, 280, 491, 41))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.startButtonciftci.setFont(custom_font)
        self.startButtonciftci.setWhatsThis("")
        self.startButtonciftci.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.startButtonciftci.setAutoRepeat(False)
        self.startButtonciftci.setAutoExclusive(False)
        self.startButtonciftci.setAutoDefault(False)
        self.startButtonciftci.setDefault(True)
        self.startButtonciftci.setFlat(False)
        self.startButtonciftci.setObjectName("startButtonciftci")
        self.sayfalar.addWidget(self.ciftciSayfa)
        self.farmSayfa = QtWidgets.QWidget()
        self.farmSayfa.setObjectName("farmSayfa")
        self.setlerGroupBox_5 = QtWidgets.QGroupBox(parent=self.farmSayfa)
        self.setlerGroupBox_5.setEnabled(True)
        self.setlerGroupBox_5.setGeometry(QtCore.QRect(0, 0, 491, 271))
        self.setlerGroupBox_5.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"border-radius:4px;")
        self.setlerGroupBox_5.setTitle("")
        self.setlerGroupBox_5.setObjectName("setlerGroupBox_5")
        self.hibritCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_5)
        self.hibritCheckBox.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.hibritCheckBox.setMouseTracking(False)
        self.hibritCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.hibritCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.hibritCheckBox.setText("")
        self.hibritCheckBox.setIcon(icon)
        self.hibritCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.hibritCheckBox.setShortcut("")
        self.hibritCheckBox.setCheckable(True)
        self.hibritCheckBox.setChecked(False)
        self.hibritCheckBox.setAutoDefault(False)
        self.hibritCheckBox.setDefault(False)
        self.hibritCheckBox.setFlat(False)
        self.hibritCheckBox.setObjectName("hibritCheckBox")
        self.label_7 = QtWidgets.QLabel(parent=self.setlerGroupBox_5)
        self.label_7.setGeometry(QtCore.QRect(45, 20, 71, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_7.setFont(custom_font)
        self.label_7.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_7.setObjectName("label_7")
        self.label_45 = QtWidgets.QLabel(parent=self.setlerGroupBox_5)
        self.label_45.setGeometry(QtCore.QRect(45, 50, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_45.setFont(custom_font)
        self.label_45.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_45.setObjectName("label_45")
        self.karpuzCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_5)
        self.karpuzCheckBox.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.karpuzCheckBox.setMouseTracking(False)
        self.karpuzCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.karpuzCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.karpuzCheckBox.setText("")
        self.karpuzCheckBox.setIcon(icon)
        self.karpuzCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.karpuzCheckBox.setShortcut("")
        self.karpuzCheckBox.setCheckable(True)
        self.karpuzCheckBox.setChecked(False)
        self.karpuzCheckBox.setAutoDefault(False)
        self.karpuzCheckBox.setDefault(False)
        self.karpuzCheckBox.setFlat(False)
        self.karpuzCheckBox.setObjectName("karpuzCheckBox")
        self.label_47 = QtWidgets.QLabel(parent=self.setlerGroupBox_5)
        self.label_47.setGeometry(QtCore.QRect(45, 80, 111, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_47.setFont(custom_font)
        self.label_47.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_47.setObjectName("label_47")
        self.kabakCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_5)
        self.kabakCheckBox.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.kabakCheckBox.setMouseTracking(False)
        self.kabakCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.kabakCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.kabakCheckBox.setText("")
        self.kabakCheckBox.setIcon(icon)
        self.kabakCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.kabakCheckBox.setShortcut("")
        self.kabakCheckBox.setCheckable(True)
        self.kabakCheckBox.setChecked(False)
        self.kabakCheckBox.setAutoDefault(False)
        self.kabakCheckBox.setDefault(False)
        self.kabakCheckBox.setFlat(False)
        self.kabakCheckBox.setObjectName("kabakCheckBox")
        self.widget_2 = QtWidgets.QWidget(parent=self.setlerGroupBox_5)
        self.widget_2.setGeometry(QtCore.QRect(10, 110, 471, 151))
        self.widget_2.setObjectName("widget_2")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 451, 31))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_8.setFont(custom_font)
        self.label_8.setStyleSheet("color:white;border:0px;")
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_9.setGeometry(QtCore.QRect(10, 34, 450, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_9.setFont(custom_font)
        self.label_9.setStyleSheet("color:white;border:0px;")
        self.label_9.setText("")
        self.label_9.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_9.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_9.setObjectName("label_9")
        self.startButtonfarm = QtWidgets.QPushButton(parent=self.farmSayfa)
        self.startButtonfarm.setGeometry(QtCore.QRect(0, 280, 491, 41))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.startButtonfarm.setFont(custom_font)
        self.startButtonfarm.setWhatsThis("")
        self.startButtonfarm.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.startButtonfarm.setAutoRepeat(False)
        self.startButtonfarm.setAutoExclusive(False)
        self.startButtonfarm.setAutoDefault(False)
        self.startButtonfarm.setDefault(True)
        self.startButtonfarm.setFlat(False)
        self.startButtonfarm.setObjectName("startButtonfarm")
        self.sayfalar.addWidget(self.farmSayfa)
        self.aletlerSayfa = QtWidgets.QWidget()
        self.aletlerSayfa.setStyleSheet("")
        self.aletlerSayfa.setObjectName("aletlerSayfa")
        self.setlerGroupBox_3 = QtWidgets.QGroupBox(parent=self.aletlerSayfa)
        self.setlerGroupBox_3.setEnabled(True)
        self.setlerGroupBox_3.setGeometry(QtCore.QRect(0, 0, 491, 271))
        self.setlerGroupBox_3.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"border-radius:4px;")
        self.setlerGroupBox_3.setTitle("")
        self.setlerGroupBox_3.setObjectName("setlerGroupBox_3")
        self.elmasKurekCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_3)
        self.elmasKurekCheckBox.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.elmasKurekCheckBox.setMouseTracking(False)
        self.elmasKurekCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.elmasKurekCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.elmasKurekCheckBox.setText("")
        self.elmasKurekCheckBox.setIcon(icon)
        self.elmasKurekCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.elmasKurekCheckBox.setShortcut("")
        self.elmasKurekCheckBox.setCheckable(True)
        self.elmasKurekCheckBox.setChecked(False)
        self.elmasKurekCheckBox.setAutoDefault(False)
        self.elmasKurekCheckBox.setDefault(False)
        self.elmasKurekCheckBox.setFlat(False)
        self.elmasKurekCheckBox.setObjectName("elmasKurekCheckBox")
        self.label_5 = QtWidgets.QLabel(parent=self.setlerGroupBox_3)
        self.label_5.setGeometry(QtCore.QRect(45, 20, 81, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_5.setFont(custom_font)
        self.label_5.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_5.setObjectName("label_5")
        self.label_34 = QtWidgets.QLabel(parent=self.setlerGroupBox_3)
        self.label_34.setGeometry(QtCore.QRect(45, 50, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_34.setFont(custom_font)
        self.label_34.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_34.setObjectName("label_34")
        self.elmasKazmaCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox_3)
        self.elmasKazmaCheckbox.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.elmasKazmaCheckbox.setMouseTracking(False)
        self.elmasKazmaCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.elmasKazmaCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.elmasKazmaCheckbox.setText("")
        self.elmasKazmaCheckbox.setIcon(icon)
        self.elmasKazmaCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.elmasKazmaCheckbox.setShortcut("")
        self.elmasKazmaCheckbox.setCheckable(True)
        self.elmasKazmaCheckbox.setChecked(False)
        self.elmasKazmaCheckbox.setAutoDefault(False)
        self.elmasKazmaCheckbox.setDefault(False)
        self.elmasKazmaCheckbox.setFlat(False)
        self.elmasKazmaCheckbox.setObjectName("elmasKazmaCheckbox")
        self.startButtonaletler = QtWidgets.QPushButton(parent=self.aletlerSayfa)
        self.startButtonaletler.setGeometry(QtCore.QRect(0, 280, 491, 41))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.startButtonaletler.setFont(custom_font)
        self.startButtonaletler.setWhatsThis("")
        self.startButtonaletler.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.startButtonaletler.setAutoRepeat(False)
        self.startButtonaletler.setAutoExclusive(False)
        self.startButtonaletler.setAutoDefault(False)
        self.startButtonaletler.setDefault(True)
        self.startButtonaletler.setFlat(False)
        self.startButtonaletler.setObjectName("startButtonaletler")
        self.sayfalar.addWidget(self.aletlerSayfa)
        self.kitaplarSayfa = QtWidgets.QWidget()
        self.kitaplarSayfa.setStyleSheet("")
        self.kitaplarSayfa.setObjectName("kitaplarSayfa")
        self.setlerGroupBox_2 = QtWidgets.QGroupBox(parent=self.kitaplarSayfa)
        self.setlerGroupBox_2.setEnabled(True)
        self.setlerGroupBox_2.setGeometry(QtCore.QRect(0, 0, 491, 271))
        self.setlerGroupBox_2.setStyleSheet("border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"border-radius:4px;")
        self.setlerGroupBox_2.setTitle("")
        self.setlerGroupBox_2.setObjectName("setlerGroupBox_2")
        self.yumruk2checkbox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.yumruk2checkbox.setGeometry(QtCore.QRect(20, 20, 16, 16))
        self.yumruk2checkbox.setMouseTracking(False)
        self.yumruk2checkbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.yumruk2checkbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.yumruk2checkbox.setText("")
        self.yumruk2checkbox.setIcon(icon)
        self.yumruk2checkbox.setIconSize(QtCore.QSize(10, 15))
        self.yumruk2checkbox.setShortcut("")
        self.yumruk2checkbox.setCheckable(True)
        self.yumruk2checkbox.setChecked(False)
        self.yumruk2checkbox.setAutoDefault(False)
        self.yumruk2checkbox.setDefault(False)
        self.yumruk2checkbox.setFlat(False)
        self.yumruk2checkbox.setObjectName("yumruk2checkbox")
        self.label_4 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_4.setGeometry(QtCore.QRect(45, 20, 71, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_4.setFont(custom_font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_4.setObjectName("label_4")
        self.label_22 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_22.setGeometry(QtCore.QRect(45, 50, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_22.setFont(custom_font)
        self.label_22.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_22.setObjectName("label_22")
        self.keskinlikCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.keskinlikCheckBox.setGeometry(QtCore.QRect(20, 50, 16, 16))
        self.keskinlikCheckBox.setMouseTracking(False)
        self.keskinlikCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.keskinlikCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.keskinlikCheckBox.setText("")
        self.keskinlikCheckBox.setIcon(icon)
        self.keskinlikCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.keskinlikCheckBox.setShortcut("")
        self.keskinlikCheckBox.setCheckable(True)
        self.keskinlikCheckBox.setChecked(False)
        self.keskinlikCheckBox.setAutoDefault(False)
        self.keskinlikCheckBox.setDefault(False)
        self.keskinlikCheckBox.setFlat(False)
        self.keskinlikCheckBox.setObjectName("keskinlikCheckBox")
        self.label_23 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_23.setGeometry(QtCore.QRect(45, 110, 111, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_23.setFont(custom_font)
        self.label_23.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_24.setGeometry(QtCore.QRect(45, 80, 111, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_24.setFont(custom_font)
        self.label_24.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_24.setObjectName("label_24")
        self.kirilmazlikCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.kirilmazlikCheckBox.setGeometry(QtCore.QRect(20, 110, 16, 16))
        self.kirilmazlikCheckBox.setMouseTracking(False)
        self.kirilmazlikCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.kirilmazlikCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.kirilmazlikCheckBox.setText("")
        self.kirilmazlikCheckBox.setIcon(icon)
        self.kirilmazlikCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.kirilmazlikCheckBox.setShortcut("")
        self.kirilmazlikCheckBox.setCheckable(True)
        self.kirilmazlikCheckBox.setChecked(False)
        self.kirilmazlikCheckBox.setAutoDefault(False)
        self.kirilmazlikCheckBox.setDefault(False)
        self.kirilmazlikCheckBox.setFlat(False)
        self.kirilmazlikCheckBox.setObjectName("kirilmazlikCheckBox")
        self.derinKosCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.derinKosCheckBox.setGeometry(QtCore.QRect(20, 80, 16, 16))
        self.derinKosCheckBox.setMouseTracking(False)
        self.derinKosCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.derinKosCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.derinKosCheckBox.setText("")
        self.derinKosCheckBox.setIcon(icon)
        self.derinKosCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.derinKosCheckBox.setShortcut("")
        self.derinKosCheckBox.setCheckable(True)
        self.derinKosCheckBox.setChecked(False)
        self.derinKosCheckBox.setAutoDefault(False)
        self.derinKosCheckBox.setDefault(False)
        self.derinKosCheckBox.setFlat(False)
        self.derinKosCheckBox.setObjectName("derinKosCheckBox")
        self.label_25 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_25.setGeometry(QtCore.QRect(45, 170, 141, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_25.setFont(custom_font)
        self.label_25.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_26.setGeometry(QtCore.QRect(45, 140, 101, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_26.setFont(custom_font)
        self.label_26.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_26.setObjectName("label_26")
        self.sonsuzlukCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.sonsuzlukCheckBox.setGeometry(QtCore.QRect(20, 170, 16, 16))
        self.sonsuzlukCheckBox.setMouseTracking(False)
        self.sonsuzlukCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.sonsuzlukCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.sonsuzlukCheckBox.setText("")
        self.sonsuzlukCheckBox.setIcon(icon)
        self.sonsuzlukCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.sonsuzlukCheckBox.setShortcut("")
        self.sonsuzlukCheckBox.setCheckable(True)
        self.sonsuzlukCheckBox.setChecked(False)
        self.sonsuzlukCheckBox.setAutoDefault(False)
        self.sonsuzlukCheckBox.setDefault(False)
        self.sonsuzlukCheckBox.setFlat(False)
        self.sonsuzlukCheckBox.setObjectName("sonsuzlukCheckBox")
        self.verimlilikCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.verimlilikCheckBox.setGeometry(QtCore.QRect(20, 140, 16, 16))
        self.verimlilikCheckBox.setMouseTracking(False)
        self.verimlilikCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.verimlilikCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.verimlilikCheckBox.setText("")
        self.verimlilikCheckBox.setIcon(icon)
        self.verimlilikCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.verimlilikCheckBox.setShortcut("")
        self.verimlilikCheckBox.setCheckable(True)
        self.verimlilikCheckBox.setChecked(False)
        self.verimlilikCheckBox.setAutoDefault(False)
        self.verimlilikCheckBox.setDefault(False)
        self.verimlilikCheckBox.setFlat(False)
        self.verimlilikCheckBox.setObjectName("verimlilikCheckBox")
        self.label_27 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_27.setGeometry(QtCore.QRect(45, 230, 91, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_27.setFont(custom_font)
        self.label_27.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_28.setGeometry(QtCore.QRect(45, 200, 121, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_28.setFont(custom_font)
        self.label_28.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_28.setObjectName("label_28")
        self.servetCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.servetCheckbox.setGeometry(QtCore.QRect(20, 230, 16, 16))
        self.servetCheckbox.setMouseTracking(False)
        self.servetCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.servetCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.servetCheckbox.setText("")
        self.servetCheckbox.setIcon(icon)
        self.servetCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.servetCheckbox.setShortcut("")
        self.servetCheckbox.setCheckable(True)
        self.servetCheckbox.setChecked(False)
        self.servetCheckbox.setAutoDefault(False)
        self.servetCheckbox.setDefault(False)
        self.servetCheckbox.setFlat(False)
        self.servetCheckbox.setObjectName("servetCheckbox")
        self.ganimetCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.ganimetCheckbox.setGeometry(QtCore.QRect(20, 200, 16, 16))
        self.ganimetCheckbox.setMouseTracking(False)
        self.ganimetCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.ganimetCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.ganimetCheckbox.setText("")
        self.ganimetCheckbox.setIcon(icon)
        self.ganimetCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.ganimetCheckbox.setShortcut("")
        self.ganimetCheckbox.setCheckable(True)
        self.ganimetCheckbox.setChecked(False)
        self.ganimetCheckbox.setAutoDefault(False)
        self.ganimetCheckbox.setDefault(False)
        self.ganimetCheckbox.setFlat(False)
        self.ganimetCheckbox.setObjectName("ganimetCheckbox")
        self.label_29 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_29.setGeometry(QtCore.QRect(190, 20, 81, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_29.setFont(custom_font)
        self.label_29.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_29.setObjectName("label_29")
        self.savurmaCheckbox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.savurmaCheckbox.setGeometry(QtCore.QRect(165, 20, 16, 16))
        self.savurmaCheckbox.setMouseTracking(False)
        self.savurmaCheckbox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.savurmaCheckbox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.savurmaCheckbox.setText("")
        self.savurmaCheckbox.setIcon(icon)
        self.savurmaCheckbox.setIconSize(QtCore.QSize(10, 15))
        self.savurmaCheckbox.setShortcut("")
        self.savurmaCheckbox.setCheckable(True)
        self.savurmaCheckbox.setChecked(False)
        self.savurmaCheckbox.setAutoDefault(False)
        self.savurmaCheckbox.setDefault(False)
        self.savurmaCheckbox.setFlat(False)
        self.savurmaCheckbox.setObjectName("savurmaCheckbox")
        self.label_33 = QtWidgets.QLabel(parent=self.setlerGroupBox_2)
        self.label_33.setGeometry(QtCore.QRect(190, 50, 101, 16))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.label_33.setFont(custom_font)
        self.label_33.setStyleSheet("color:rgba(255, 255, 255, 0.8);\n"
"border:0px")
        self.label_33.setObjectName("label_33")
        self.korumaCheckBox = QtWidgets.QPushButton(parent=self.setlerGroupBox_2)
        self.korumaCheckBox.setGeometry(QtCore.QRect(165, 50, 16, 16))
        self.korumaCheckBox.setMouseTracking(False)
        self.korumaCheckBox.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.korumaCheckBox.setStyleSheet("border: 1px solid rgba(48, 213, 200, 0.8);")
        self.korumaCheckBox.setText("")
        self.korumaCheckBox.setIcon(icon)
        self.korumaCheckBox.setIconSize(QtCore.QSize(10, 15))
        self.korumaCheckBox.setShortcut("")
        self.korumaCheckBox.setCheckable(True)
        self.korumaCheckBox.setChecked(False)
        self.korumaCheckBox.setAutoDefault(False)
        self.korumaCheckBox.setDefault(False)
        self.korumaCheckBox.setFlat(False)
        self.korumaCheckBox.setObjectName("korumaCheckBox")
        self.startButtonkitaplar = QtWidgets.QPushButton(parent=self.kitaplarSayfa)
        self.startButtonkitaplar.setGeometry(QtCore.QRect(0, 280, 491, 41))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.startButtonkitaplar.setFont(custom_font)
        self.startButtonkitaplar.setWhatsThis("")
        self.startButtonkitaplar.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:2px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.startButtonkitaplar.setAutoRepeat(False)
        self.startButtonkitaplar.setAutoExclusive(False)
        self.startButtonkitaplar.setAutoDefault(False)
        self.startButtonkitaplar.setDefault(True)
        self.startButtonkitaplar.setFlat(False)
        self.startButtonkitaplar.setObjectName("startButtonkitaplar")
        self.sayfalar.addWidget(self.kitaplarSayfa)
        self.aletlerBtn = QtWidgets.QPushButton(parent=self.arkaplan)
        self.aletlerBtn.setGeometry(QtCore.QRect(120, 50, 95, 35))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.aletlerBtn.setFont(custom_font)
        self.aletlerBtn.setWhatsThis("")
        self.aletlerBtn.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.aletlerBtn.setAutoRepeat(False)
        self.aletlerBtn.setAutoExclusive(False)
        self.aletlerBtn.setAutoDefault(False)
        self.aletlerBtn.setDefault(True)
        self.aletlerBtn.setFlat(False)
        self.aletlerBtn.setObjectName("aletlerBtn")
        self.ciftciBtn = QtWidgets.QPushButton(parent=self.arkaplan)
        self.ciftciBtn.setGeometry(QtCore.QRect(320, 50, 95, 35))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.ciftciBtn.setFont(custom_font)
        self.ciftciBtn.setWhatsThis("")
        self.ciftciBtn.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.ciftciBtn.setAutoRepeat(False)
        self.ciftciBtn.setAutoExclusive(False)
        self.ciftciBtn.setAutoDefault(False)
        self.ciftciBtn.setDefault(True)
        self.ciftciBtn.setFlat(False)
        self.ciftciBtn.setObjectName("ciftciBtn")
        self.farmBtn = QtWidgets.QPushButton(parent=self.arkaplan)
        self.farmBtn.setGeometry(QtCore.QRect(420, 50, 93, 35))
        font = QtGui.QFont()
        
        font.setPointSize(12)
        self.farmBtn.setFont(custom_font)
        self.farmBtn.setWhatsThis("")
        self.farmBtn.setStyleSheet("QPushButton{\n"
"border: 1px solid rgba(255, 255, 255, 0.2);\n"
"background-color:rgb(14,14,14);\n"
"color:white;\n"
"border-radius:4px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgba(255,255,255,0.1);\n"
"border: 1px solid rgba(255,255,255,1);\n"
"}")
        self.farmBtn.setAutoRepeat(False)
        self.farmBtn.setAutoExclusive(False)
        self.farmBtn.setAutoDefault(False)
        self.farmBtn.setDefault(True)
        self.farmBtn.setFlat(False)
        self.farmBtn.setObjectName("farmBtn")
        self.sayfalar.raise_()
        self.aletlerBtn.raise_()
        self.kitaplarBtn.raise_()
        self.ciftciBtn.raise_()
        self.farmBtn.raise_()
        self.setlerBtn.raise_()
        enchantForm.setCentralWidget(self.setler)

        self.retranslateUi(enchantForm)
        self.sayfalar.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(enchantForm)

    def retranslateUi(self, enchantForm):
        _translate = QtCore.QCoreApplication.translate
        enchantForm.setWindowTitle(_translate("enchantForm", "FClient v0.0.4"))
        self.kitaplarBtn.setText(_translate("enchantForm", "Kitaplar"))
        self.setlerBtn.setText(_translate("enchantForm", "Setler"))
        self.label_3.setText(_translate("enchantForm", "Elmas kask"))
        self.label_14.setText(_translate("enchantForm", "Elmas Chestplate"))
        self.label_15.setText(_translate("enchantForm", "Elmas Bot"))
        self.label_16.setText(_translate("enchantForm", "Elmas pantalon"))
        self.label_17.setText(_translate("enchantForm", "Titanyum chestplate"))
        self.label_18.setText(_translate("enchantForm", "Titanyum kask"))
        self.label_19.setText(_translate("enchantForm", "Titanyum bot"))
        self.label_20.setText(_translate("enchantForm", "Titanyum pantalon"))
        self.label_21.setText(_translate("enchantForm", "Elmas kilic"))
        self.label_30.setText(_translate("enchantForm", "Yay"))
        self.label_31.setText(_translate("enchantForm", "Titanyum kilic"))
        self.startButtonsetler.setText(_translate("enchantForm", "Baslat"))
        self.label_6.setText(_translate("enchantForm", "Karpuz (Sag tikla satar)"))
        self.label_44.setText(_translate("enchantForm", "Kabak (Envantere alip satar)"))
        self.label.setText(_translate("enchantForm", "Ekran cozunurlugu 1920x1080  olmasi gerekmekte (minimum 2 hesap)"))
        self.label_2.setText(_translate("enchantForm", "Dil ayarlarından unicodeu açın ekranı pencereli yapıpı büyütün!"))
        self.startButtonciftci.setText(_translate("enchantForm", "Baslat"))
        self.label_7.setText(_translate("enchantForm", "Hibrit"))
        self.label_45.setText(_translate("enchantForm", "Karpuz"))
        self.label_47.setText(_translate("enchantForm", "Kabak"))
        self.label_8.setText(_translate("enchantForm", "Yakinda acilacak su anda bakimda!"))
        self.startButtonfarm.setText(_translate("enchantForm", "Baslat"))
        self.label_5.setText(_translate("enchantForm", "Elmas kurek"))
        self.label_34.setText(_translate("enchantForm", "Elmas kazma"))
        self.startButtonaletler.setText(_translate("enchantForm", "Baslat"))
        self.label_4.setText(_translate("enchantForm", "Yumruk II"))
        self.label_22.setText(_translate("enchantForm", "Keskinlik IV"))
        self.label_23.setText(_translate("enchantForm", "Kirilmazlik III"))
        self.label_24.setText(_translate("enchantForm", "Derin kosucu III"))
        self.label_25.setText(_translate("enchantForm", "Sonsuzluk I"))
        self.label_26.setText(_translate("enchantForm", "Verimlilik IV"))
        self.label_27.setText(_translate("enchantForm", "Servet III"))
        self.label_28.setText(_translate("enchantForm", "Ganimet III"))
        self.label_29.setText(_translate("enchantForm", "Savurma II"))
        self.label_33.setText(_translate("enchantForm", "Koruma IV"))
        self.startButtonkitaplar.setText(_translate("enchantForm", "Baslat"))
        self.aletlerBtn.setText(_translate("enchantForm", "Aletler"))
        self.ciftciBtn.setText(_translate("enchantForm", "Çiftçi"))
        self.farmBtn.setText(_translate("enchantForm", "Farm"))








        print(cozunurluk)
        def tit_kask_check_box():
             if bot.tit_kask_durum == False:
                  bot.tit_kask_durum = True
                  diaset1366.tit_cp_durum = True
             elif bot.tit_kask_durum == True:
                  bot.tit_kask_durum = False
                  diaset1366.tit_kask_durum = False


        def tit_cp_check_box():
             if bot.tit_cp_durum == False:
                  bot.tit_cp_durum = True
                  diaset1366.tit_cp_durum = True
             elif bot.tit_cp_durum == True:
                  bot.tit_cp_durum = False
                  diaset1366.tit_cp_durum = False

        def tit_pant_check_box():
             if bot.tit_pant_durum == False:
                  bot.tit_pant_durum = True
                  diaset1366.tit_kask_durum = True
             elif bot.tit_pant_durum == True:
                  bot.tit_kask_durum == False
                  diaset1366.tit_kask_durum = False

        def tit_bot_check_box():
             if bot.tit_bot_durum == False:
                  bot.tit_bot_durum = True
                  diaset1366.tit_bot_durum = True
             elif bot.tit_bot_durum == True:
                  bot.tit_bot_durum = False
                  diaset1366.tit_bot_durum = False
        
        def dia_kask_check_box():
             if bot.dia_kask_durum == False:
                  bot.dia_kask_durum = True
                  diaset1366.dia_kask_durum = True
             elif bot.dia_kask_durum == True:
                  bot.dia_kask_durum = False
                  diaset1366.dia_kask_durum = False

        def dia_cp_check_box():
             if bot.dia_cp_durum == False:
                  bot.dia_cp_durum = True
                  diaset1366.dia_cp_durum = True
             elif bot.dia_cp_durum == True:
                  bot.dia_cp_durum = False
                  diaset1366.dia_cp_durum = False

        def dia_pant_check_box():
             if bot.dia_pant_durum == False:
                  bot.dia_pant_durum = True
                  diaset1366.dia_pant_durum = True
             elif bot.dia_pant_durum == True:
                  bot.dia_pant_durum = False
                  diaset1366.dia_pant_durum = False

        def dia_bot_check_box():
             if bot.dia_bot_durum == False:
                  bot.dia_bot_durum = True
                  diaset1366.dia_bot_durum = True
             elif bot.dia_bot_durum == True:
                  bot.dia_bot_durum = False
                  diaset1366.dia_bot_durum = False

        def dia_kazma_check_box():
             if aletlerr.dia_kazma_durum == False:
                  aletlerr.dia_kazma_durum = True
                  aletler1366.dia_kazma_durum = True
             elif aletlerr.dia_kazma_durum == True:
                  aletlerr.dia_kazma_durum = False
                  aletler1366.dia_kazma_durum = False

        def dia_kurek_check_box():
             if aletlerr.dia_kurek_durum == False:
                  aletlerr.dia_kurek_durum = True
                  aletlerr.dia_kurek_durum = True
             elif aletlerr.dia_kurek_durum == True:
                  aletlerr.dia_kurek_durum = False
                  aletlerr.dia_kurek_durum = False

        def dia_balta_check_box():
             if bot.dia_balta_durum == False:
                  bot.dia_balta_durum = True
                  diaset1366.dia_balta_durum = True
             elif bot.dia_balta_durum == True:
                  bot.dia_balta_durum = False
                  diaset1366.dia_balta_durum = False

        def dia_kilic_check_box():
             if bot.dia_kilic_durum == False:
                  bot.dia_kilic_durum = True
                  diaset1366.dia_kilic_durum = True
             elif bot.dia_kilic_durum == True:
                  bot.dia_kilic_durum = False
                  diaset1366.dia_kilic_durum = False

        def yay_check_box():
             if bot.yay_durum == False:
                  bot.yay_durum = True
                  diaset1366.yay_durum = True
             elif bot.yay_durum == True:
                  bot.yay_durum = False
                  diaset1366.yay_durum = False


        def titanyum_kurek_check_box():
             if aletlerr.titanyum_kurek_durum == False:
                  aletlerr.titanyum_kurek_durum = True
             elif aletlerr.titanyum_kurek_durum == True:
                  aletlerr.titanyum_kurek_durum = False

        def savas_baltasi_check_box():
             if aletlerr.savas_baltasi_durum == False:
                  aletlerr.savas_baltasi_durum = True
             elif aletlerr.savas_baltasi_durum == True:
                  aletlerr.savas_baltasi_durum = False

        def titanyum_kazma_check_box():
             if aletlerr.titanyum_kazma_durum == False:
                  aletlerr.titanyum_kazma = True
             elif aletlerr.titanyum_kazma == True:
                  aletlerr.titanyum_kazma = False

        def titanyum_balta_check_box():
             if aletlerr.titanyum_balta_durum == False:
                  aletlerr.titanyum_balta_durum = True
             elif aletlerr.titanyum_balta_durum == True:
                  aletlerr.titanyum_balta_durum = False


        def yumruk_kitap_check_box():
             if kitap.yumruk_durum == False:
                  kitap.yumruk_durum = True
                  kitap1366.yumruk_durum = True
             elif kitap.yumruk_durum == True:
                  kitap.yumruk_durum = False
                  kitap1366.yumruk_durum = False

        def keskinlik_kitap_check_box():
             if kitap.keskinlik_durum == False:
                  kitap.keskinlik_durum = True
                  kitap1366.keskinlik_durum = True
             elif kitap.keskinlik_durum == True:
                  kitap.keskinlik_durum = False
                  kitap1366.keskinlik_durum = False
        def koruma_check_box():
             if kitap.koruma_durum == False:
                  kitap.koruma_durum = True
                  kitap1366.koruma_durum = True
             elif kitap.koruma_durum == True:
                  kitap.koruma_durum = False
                  kitap1366.koruma_durum = False
                  
        def kirilmazlik_kitap_check_box():
             if kitap.kirilmazlik_durum == False:
                  kitap.kirilmazlik_durum = True
                  kitap1366.kirilmazlik_durum = True
             elif kitap.kirilmazlik_durum == True:
                  kitap.kirilmazlik_durum = False
                  kitap1366.kirilmazlik_durum = False

        def derinkos_kitap_check_box():
             if kitap.derin_kosucu_durum == False:
                  kitap.derin_kosucu_durum = True
                  kitap1366.derin_kosucu_durum = True
             elif kitap.derin_kosucu_durum == True:
                  kitap.derin_kosucu_durum = False
                  kitap1366.derin_kosucu_durum = False

        def sonsuzluk_kitap_check_box():
             global sonsuzluk_durum
             if kitap.sonsuzluk_durum == False:
                  kitap.sonsuzluk_durum = True
                  kitap1366.sonsuzluk_durum = True
             elif kitap.sonsuzluk_durum == True:
                  kitap.sonsuzluk_durum = False
                  kitap1366.sonsuzluk_durum = False

        def verimlilik_kitap_check_box():
             if kitap.verimlilik_durum == False:
                  kitap.verimlilik_durum = True
                  kitap1366.verimlilik_durum = True
             elif kitap.verimlilik_durum == True:
                  kitap.verimlilik_durum = False
                  kitap1366.verimlilik_durum = False

        def t_kilic_check_box():
             if bot.tit_kilic_durum == False:
                  bot.tit_kilic_durum = True
                  bot.tit_kilic_durum = True
             elif kitap.verimlilik_durum == True:
                  bot.tit_kilic_durum = False
                  bot.tit_kilic_durum = False

        def servet_kitap_check_box():
             if kitap.servet_durum == False:
                  kitap.servet_durum = True
                  kitap1366.servet_durum = True
             elif kitap.servet_durum == True:
                  kitap.servet_durum = False
                  kitap1366.servet_durum = False

        def ganimet_kitap_check_box():
             if kitap.ganimet_durum == False:
                  kitap.ganimet_durum = True
                  kitap1366.ganimet_durum = True
             elif kitap.ganimet_durum == True:
                  kitap.ganimet_durum = False
                  kitap1366.ganimet_durum = False

        def savurma_kitap_check_box():
             if kitap.savurma_durum == False:
                  kitap.savurma_durum = True
                  kitap1366.savurma_durum = True
             elif kitap.savurma_durum == True:
                  kitap.savurma_durum = False
                  kitap1366.savurma_durum = False
        def ipeksi_kitap_check_box():
             if kitap.ipeksi_durum == False:
                  kitap.ipeksi_durum = True
                  kitap1366.ipeksi_durum = True
             elif kitap.ipeksi_durum == True:
                  kitap.ipeksi_durum = False
                  kitap1366.ipeksi_durum = False

        def alet_start():
          if cozunurluk == "1920x1080":
             aletlerr.main()
          elif cozunurluk == "1366x768":
             aletler1366.main()

        def setler_start():
          if cozunurluk == "1920x1080":
             bot.main()
          elif cozunurluk == "1366x768":
             diaset1366.main()

        def kitap_start():
          if cozunurluk == "1920x1080":
             kitap.main()
          elif cozunurluk == "1366x768":
             kitap1366.main()
         
             
        self.startButtonkitaplar.clicked.connect(kitap_start)

        self.startButtonaletler.clicked.connect(alet_start)
        self.elmasKurekCheckBox.clicked.connect(dia_kurek_check_box)


        self.startButtonsetler.clicked.connect(setler_start)

        self.titkaskCheckbox.clicked.connect(tit_kask_check_box)
        self.titChestPlateCheckBox.clicked.connect(tit_cp_check_box)
        self.titpantCheckbox.clicked.connect(tit_pant_check_box)
        self.titbotCheckbox.clicked.connect(tit_bot_check_box)
        self.startButtonciftci.clicked.connect(ciftcimain.main)
        self.startButtonfarm.clicked.connect(otofarm.main)

        self.diakaskCheckbox.clicked.connect(dia_kask_check_box)
        self.diaChestPlateCheckbox.clicked.connect(dia_cp_check_box)
        self.diapntCheckbox.clicked.connect(dia_pant_check_box)
        self.diabotCheckbox.clicked.connect(dia_bot_check_box)

        self.kilicCheckbox.clicked.connect(dia_kilic_check_box)
        self.yayCheckbox.clicked.connect(yay_check_box)

        self.elmasKazmaCheckbox.clicked.connect(dia_kazma_check_box)
        self.korumaCheckBox.clicked.connect(koruma_check_box)


        #self.elmasKazmaCheckbox.clicked.connect(dia_kazma_check_box)
        #self.elmasbaltaCheckbox.clicked.connect(dia_balta_check_box)
        #self.elmasKilicCheckbox.clicked.connect(dia_kilic_check_box)

        #self.titanyumKazmaCheckbox.clicked.connect(titanyum_kazma_check_box)
        #self.TitanyumBaltaCheckbox.clicked.connect(titanyum_balta_check_box)
        #self.titanyumKurekCheckbox_2.clicked.connect(titanyum_kurek_check_box)
        #self.titanyumSavasBaltasi.clicked.connect(savas_baltasi_check_box)

        self.yumruk2checkbox.clicked.connect(yumruk_kitap_check_box)
        self.keskinlikCheckBox.clicked.connect(keskinlik_kitap_check_box)
        self.kirilmazlikCheckBox.clicked.connect(kirilmazlik_kitap_check_box)
        self.derinKosCheckBox.clicked.connect(derinkos_kitap_check_box)

        self.sonsuzlukCheckBox.clicked.connect(sonsuzluk_kitap_check_box)
        self.verimlilikCheckBox.clicked.connect(verimlilik_kitap_check_box)
        self.servetCheckbox.clicked.connect(servet_kitap_check_box)
        self.ganimetCheckbox.clicked.connect(ganimet_kitap_check_box)
        self.titanyumKilicCheckBox.clicked.connect(t_kilic_check_box)

        self.savurmaCheckbox.clicked.connect(savurma_kitap_check_box)
        #self.ipeksiCheckbox.clicked.connect(ipeksi_kitap_check_box)
        

        def Sayfa_Degis():
            self.setlerBtn.clicked.connect(lambda: self.sayfalar.setCurrentWidget(self.setlerSayfa))
            self.aletlerBtn.clicked.connect(lambda: self.sayfalar.setCurrentWidget(self.aletlerSayfa))
            self.kitaplarBtn.clicked.connect(lambda: self.sayfalar.setCurrentWidget(self.kitaplarSayfa))
            self.ciftciBtn.clicked.connect(lambda: self.sayfalar.setCurrentWidget(self.ciftciSayfa))
            self.farmBtn.clicked.connect(lambda: self.sayfalar.setCurrentWidget(self.farmSayfa))
        
        Sayfa_Degis()
        

class AletlerApp(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_aletler()
        self.ui.setupUi(self)

if __name__ == "__main__":
    app = QtWidgets.QApplication([])
    window = AletlerApp()
    window.show()
    app.exec()
